name: donaid
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  favorite_button: ^0.0.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.1.0
  flutter_facebook_auth: ^4.0.1
  google_sign_in: ^5.2.3
  flutter_signin_button: ^2.0.0
  flutter_easyloading: ^3.0.3
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_storage: ^10.2.7

  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  country_picker: ^2.0.11
  image_picker: ^0.8.4+8
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.20

  get:
  get_storage: ^2.0.3
  dio: ^4.0.4
  bubble:
  google_fonts:
  random_string:
  firebase_database:
  circle_wheel_scroll:
  flutter_sliding_up_panel: ^2.0.1
  circle_list:
  auto_size_text:
  bottom_drawer:
  modal_bottom_sheet:
  top_modal_sheet:

  flutter_stripe: ^2.2.0
  http: ^0.13.4
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

